<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Slip - {{ $patient->patient_id }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 20px;
        }
        .container {
            width: 100%;
            max-width: 700px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ddd;
        }
        h2 {
            text-align: center;
            color: #333;
        }
        .header {
            text-align: center;
            font-size: 18px;
            margin-bottom: 20px;
        }
        .details-table {
            width: 100%;
            border-collapse: collapse;
        }
        .details-table th, .details-table td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        .details-table th {
            background-color: #f2f2f2;
        }
        .footer {
            text-align: center;
            font-size: 14px;
            margin-top: 20px;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="header">
        <h2>Patient Slip</h2>
        <p><strong>Slip Date:</strong> {{ date('d-m-Y', strtotime($patient->slip_date)) }}</p>
    </div>

    <table class="details-table">
        <tr>
            <th>Patient ID</th>
            <td>{{ $patient->patient_id }}</td>
        </tr>
        <tr>
            <th>Patient Name</th>
            <td>{{ $patient->patient_name }}</td>
        </tr>
        <tr>
            <th>Age</th>
            <td>{{ $patient->age }}</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>{{ $patient->gender }}</td>
        </tr>
        <tr>
            <th>Contact No</th>
            <td>{{ $patient->contact_no }}</td>
        </tr>
        <tr>
            <th>Procedure Name</th>
            <td>{{ $patient->procedure_name }}</td>
        </tr>
        <tr>
            <th>Referring Physician</th>
            <td>{{ $patient->ref_phy ?? 'N/A' }}</td>
        </tr>
        <tr>
            <th>Patient History</th>
            <td>{{ $patient->patient_history ?? 'N/A' }}</td>
        </tr>
        <tr>
            <th>Total Amount</th>
            <td>{{ number_format($patient->total_amount, 2) }} PKR</td>
        </tr>
        <tr>
            <th>Discount</th>
            <td>{{ number_format($patient->discount, 2) }} PKR</td>
        </tr>
        <tr>
            <th>Cash Received</th>
            <td>{{ number_format($patient->cash_received, 2) }} PKR</td>
        </tr>
        <tr>
            <th>Dues</th>
            <td>{{ number_format($patient->dues, 2) }} PKR</td>
        </tr>
    </table>

    <div class="footer">
        <p>Generated by Hospital Management System</p>
    </div>
</div>

</body>
</html>
